export const INIT_BOOKS = 'INIT_BOOKS';
export const INIT_BOOKS_FAIL = 'INIT_BOOKS_FAIL';
export const INIT_BOOKS_SUCCESS = 'INIT_BOOKS_SUCCESS';
export const INITIALIZE_BOOKS = 'INITIALIZE_BOOKS';

export const INITIALIZE_REVIEWS = 'INITIALIZE_REVIEWS';
export const INIT_REVIEWS = 'INIT_REVIEWS';
export const INIT_REVIEWS_SUCCESS = 'INIT_REVIEWS_SUCCESS';
export const INIT_REVIEWS_FAIL = 'INIT_REVIEWS_FAIL';

export const BOOK_LIKE_CHECK = 'BOOK_LIKE_CHECK'
export const BOOK_LIKE_CHECK_INIT = 'BOOK_LIKE_CHECK_INIT';

export const INITIALIZE_LOGIN = 'INITIALIZE_LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHECK_LOGIN_TIMEOUT = 'CHECK_LOGIN_TIMEOUT';
export const CHECK_LOGIN_STATE = 'CHECK_LOGIN_STATE';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const INITIALIZE_REGISTER = 'INITIALIZE_REGISTER';
export const REGISTER_RESET = 'REGISTER_RESET';

export const INITIATE_LOGOUT = 'INITIATE_LOGOUT';
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED';
export const SET_LOGIN_REDIRECT_PATH = 'SET_LOGIN_REDIRECT_PATH';